version: "3.0"
services:
  cart:
    image: ghcr.io/sbk-cloud-services/cart-microservice:latest
    build:
      context: .
    links:
      - database
    ports:
      - "127.0.0.1:8080:8080"

  database:
    volumes:
      - database:/var/lib/mysql
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
      MYSQL_DATABASE: cart
      MYSQL_USER: cart
      MYSQL_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
    ports:
      - "127.0.0.1:3306:3306"
volumes:
  database:
